# Generated by Django 2.1.7 on 2019-03-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0003_auto_20190302_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_datetime',
            new_name='task_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
    ]
